# Generated by Django 5.2.3 on 2025-06-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_date_of_birth_user_full_name_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='focus_area',
            field=models.CharField(blank=True, choices=[('H', 'Health'), ('W', 'Wealth'), ('R', 'Relationships'), ('C', 'Career'), ('S', 'Spirituality')], max_length=1),
        ),
    ]
